version: '3.8'

services:
  tg_app:
    container_name: tg_app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - tg_db

  tg_db:
    container_name: tg_db
    image: postgres:latest
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
